# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Opis')),
                ('url', models.SlugField(blank=True, verbose_name='url')),
                ('status', models.BooleanField(verbose_name='Status')),
                ('img', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slide_img', to='filer.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tytuł')),
                ('home', models.BooleanField(verbose_name='Strona główna')),
                ('status', models.BooleanField(verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Slidery',
            },
        ),
        migrations.AddField(
            model_name='slide',
            name='slider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sliders.Slider', verbose_name='Slider'),
        ),
    ]
