# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Tytuł'),
            preserve_default=False,
        ),
    ]
