# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 16:57
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('festivals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kategoria')),
                ('status', models.BooleanField(verbose_name='Status')),
            ],
            options={
                'verbose_name_plural': 'Kategorie',
                'verbose_name': 'Kategoria',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField(blank=True, unique_for_date='pub_date', verbose_name='url')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Tytuł')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='Data publikacji')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='Seo tytuł :)')),
                ('seo_keywords', models.CharField(blank=True, max_length=255, verbose_name='Seo słowa kluczowe :)')),
                ('seo_description', models.TextField(blank=True, verbose_name='Seo opis :)')),
                ('status', models.BooleanField(verbose_name='Status')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Category', verbose_name='Kategoria')),
                ('festivals', models.ManyToManyField(to='festivals.Festival', verbose_name='Festiwale')),
                ('img', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_img', to='filer.Image')),
            ],
            options={
                'verbose_name_plural': 'Artykuły',
                'verbose_name': 'Artykuł',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tag')),
                ('status', models.BooleanField(verbose_name='Status')),
            ],
            options={
                'verbose_name_plural': 'Tagi',
                'verbose_name': 'Tag',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(to='news.Tag', verbose_name='Tagi'),
        ),
        migrations.AddField(
            model_name='news',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
    ]
