# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 16:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'kategoria', 'verbose_name_plural': 'kategorie'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Artykuł', 'verbose_name_plural': 'Artykuł'},
        ),
        migrations.AddField(
            model_name='news',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
