# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 17:13
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170213_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Category', verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(blank=True, verbose_name='Data publikacji'),
        ),
        migrations.AlterField(
            model_name='news',
            name='seo_description',
            field=models.TextField(blank=True, verbose_name='Seo opis :)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='Seo słowa kluczowe :)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Seo tytuł :)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.SlugField(blank=True, unique_for_date='pub_date', verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='news',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
    ]
