# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20170213_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data publikacji'),
        ),
    ]
