# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20170213_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tagi',
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Artykuł', 'verbose_name_plural': 'Artykuły'},
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(to='news.Tag', verbose_name='Tagi'),
        ),
    ]
