# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_news_festiwals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoria', 'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=1, verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Kategoria'),
        ),
    ]
