# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20170220_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='status',
            field=models.BooleanField(default=1, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
