# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festiwals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='festiwals',
            options={'verbose_name': 'Festiwal', 'verbose_name_plural': 'Festiwale'},
        ),
        migrations.AlterField(
            model_name='festiwals',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nazwa festiwalu'),
        ),
    ]
