# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 16:57
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Tytuł')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='Seo tytuł :)')),
                ('seo_keywords', models.CharField(blank=True, max_length=255, verbose_name='Seo słowa kluczowe :)')),
                ('seo_description', models.TextField(blank=True, verbose_name='Seo opis :)')),
                ('status', models.BooleanField(verbose_name='Status')),
                ('img', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist_img', to='filer.Image')),
            ],
            options={
                'verbose_name_plural': 'Artyści',
                'verbose_name': 'Artysta',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kategoria')),
                ('status', models.BooleanField(verbose_name='Status')),
            ],
            options={
                'verbose_name_plural': 'Kategorie',
                'verbose_name': 'Kategoria',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kraj')),
                ('status', models.BooleanField(verbose_name='Status')),
            ],
            options={
                'verbose_name_plural': 'Kraje',
                'verbose_name': 'Kraj',
            },
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField(blank=True, unique_for_date='pub_date_start', verbose_name='url')),
                ('title', models.CharField(max_length=255, verbose_name='Nazwa festiwalu')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Opis')),
                ('pub_date_start', models.DateTimeField(blank=True, null=True, verbose_name='Data rozpoczęcia')),
                ('pub_date_end', models.DateTimeField(blank=True, null=True, verbose_name='Data zakończenia')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='Seo tytuł :)')),
                ('seo_keywords', models.CharField(blank=True, max_length=255, verbose_name='Seo słowa kluczowe :)')),
                ('seo_description', models.TextField(blank=True, verbose_name='Seo opis :)')),
                ('artists', models.ManyToManyField(to='festivals.Artist', verbose_name='Artyści')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='festivals.Category', verbose_name='Kategoria')),
                ('img', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='festiwal_img', to='filer.Image')),
            ],
            options={
                'verbose_name_plural': 'Festiwale',
                'verbose_name': 'Festiwal',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tag')),
                ('status', models.BooleanField(verbose_name='Status')),
            ],
            options={
                'verbose_name_plural': 'Tagi',
                'verbose_name': 'Tag',
            },
        ),
        migrations.AddField(
            model_name='festival',
            name='tags',
            field=models.ManyToManyField(to='festivals.Tag', verbose_name='Tagi'),
        ),
    ]
