# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='festivals.Country', verbose_name='Kraj'),
        ),
    ]
