# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0002_tag_status2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='status2',
        ),
    ]
