# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0003_festival_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='festival',
            options={'get_latest_by': 'pub_date_start', 'ordering': ('pub_date_start',), 'verbose_name': 'Festiwal', 'verbose_name_plural': 'Festiwale'},
        ),
        migrations.AddField(
            model_name='festival',
            name='address',
            field=models.CharField(default=1, max_length=255, verbose_name='Adres'),
            preserve_default=False,
        ),
    ]
