# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0003_remove_tag_status2'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='status2',
            field=models.BooleanField(default=1, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
