# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0006_artist_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='url',
            field=models.SlugField(blank=True, verbose_name='url'),
        ),
    ]
